-- 코드를 작성해주세요
SELECT ID, COUNT(CHILD) AS CHILD_COUNT
FROM (SELECT PARENT.ID AS ID, CHILD.PARENT_ID AS CHILD
FROM ECOLI_DATA AS PARENT, ECOLI_DATA AS CHILD
WHERE CHILD.PARENT_ID = PARENT.ID) SUB
GROUP BY CHILD

UNION

SELECT PARENT.ID AS ID, 0 AS CHILD_COUNT
FROM ECOLI_DATA AS PARENT, ECOLI_DATA AS CHILD
WHERE PARENT.ID NOT IN (SELECT PARENT.ID AS ID
                        FROM ECOLI_DATA AS PARENT, ECOLI_DATA AS CHILD
                        WHERE CHILD.PARENT_ID = PARENT.ID)

ORDER BY ID