-- 코드를 작성해주세요
SELECT YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) AS YEAR, (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ECOLI_DATA.ID
FROM ECOLI_DATA, (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA
GROUP BY YEAR
HAVING MAX(SIZE_OF_COLONY)) GROUP_MAX
WHERE YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = GROUP_MAX.YEAR
ORDER BY YEAR, YEAR_DEV