-- 코드를 작성해주세요 
-- 피쉬 타입 그룹바이 해서 맥스값인 거
-- SELECT ID, FISH_NAME, MAX(LENGTH)
-- FROM (SELECT FISH_INFO.ID AS ID, FISH_NAME_INFO.FISH_NAME AS FISH_NAME, FISH_INFO.LENGTH AS LENGTH
-- FROM FISH_INFO, FISH_NAME_INFO
-- WHERE FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE) NAME_LENGTH
-- GROUP BY FISH_NAME
-- -> GROUP BY에 ID 없어서 안 됨

SELECT FISH_INFO.ID AS ID, FISH_NAME_INFO.FISH_NAME AS FISH_NAME, FISH_INFO.LENGTH AS LENGTH
FROM FISH_INFO, FISH_NAME_INFO, (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
      FROM FISH_INFO
      GROUP BY FISH_TYPE) MAX_FISH
WHERE FISH_INFO.FISH_TYPE = MAX_FISH.FISH_TYPE AND FISH_INFO.LENGTH = MAX_FISH.LENGTH AND FISH_NAME_INFO.FISH_TYPE = MAX_FISH.FISH_TYPE
